

install:
	- virtualenv trabalho1        
	- ( \
       . trabalho1/bin/activate; \
       pip3 install -U -r requirements.txt; \
    )
run:
	- ( \
       . trabalho1/bin/activate; \
      python3 ex4_log_reg.py \
    )