

install:
	- virtualenv ../SkitLearnAndTensorFlow
	- ( \
       . bin/activate; \
       pip3 install -U -r requirements.txt; \
    )
run:
	- ( \
       . bin/activate; \
      python3 datasets.py \
    )