

install:
	- virtualenv -p python3 trabalho2     
	- ( \
       . trabalho2/bin/activate; \
       pip3 install -U -r requirements.txt; \
    )
run:
	- ( \
       . trabalho2/bin/activate; \
      python3 ex4_log_reg.py \
    )